# Generated by Django 4.0.4 on 2022-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=15, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
