# Generated by Django 4.0.5 on 2022-06-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('discrib', models.CharField(max_length=200, null=True)),
                ('data_create', models.DateTimeField(
                    auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('sstatus', models.CharField(choices=[('pending', 'pending'), (
                    'delivered', 'delivered'), ('in progress', 'inprograss')], max_length=200, null=True)),
            ],
        ),
    ]
