# Generated by Django 4.0.5 on 2022-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_tag_order_b_order_cus_order_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='t',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
    ]
